Repository eclipse-score/score, pull requests merged in 2025-04, with the labels that each got.

#713 process: add testing independence to verification plan
  docs/platform_management_plan/software_verification.rst
Labels: community:testing, community:process

#792 process: adjust test levels and methods
  docs/platform_management_plan/software_verification.rst
  docs/process/process_areas/verification/guidance/verification_process_toolreqs.rst
  docs/process/process_areas/verification/verification_concept.rst
  docs/process/process_areas/verification/workproducts.rst
Labels: community:testing, community:process

#721 process: verification guide for types and methods
  docs/platform_management_plan/software_verification.rst
  docs/process/process_areas/implementation/guidance/implementation_checklist.rst
  docs/process/process_areas/verification/guidance/index.rst
  docs/process/process_areas/verification/guidance/verification_guideline.rst
  docs/process/process_areas/verification/guidance/verification_methods.rst
  docs/process/process_areas/verification/guidance/verification_process_toolreqs.rst
  docs/process/process_areas/verification/verification_concept.rst
Labels: community:testing, community:process

#954 docs: fix test execution via pytest from venv
  .vscode/settings.json
  docs/_tooling/extensions/score_metamodel/__init__.py
  docs/_tooling/extensions/score_metamodel/tests/README.md
  docs/_tooling/extensions/score_metamodel/tests/rst/conf.py
  docs/_tooling/extensions/score_metamodel/tests/rst/graph/test_metamodel_graph.rst
  docs/_tooling/extensions/score_metamodel/tests/rst/options/test_options_extra_option.rst
  docs/_tooling/extensions/score_metamodel/tests/rst/options/test_options_options.rst
  docs/_tooling/extensions/score_metamodel/tests/test_rules_file_based.py
  docs/conf.py
  pyproject.toml
Labels: community:infrastructure, needs-rework

#980 tooling: Add new test files for check rule tests
  docs/_tooling/extensions/score_metamodel/__init__.py
  docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_description.rst
  docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_id_format.rst
  docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_id_length.rst
  docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_title.rst
  docs/_tooling/extensions/score_metamodel/tests/rst/graph/test_metamodel_graph.rst
  docs/_tooling/extensions/score_metamodel/tests/rst/id_contains_feature/test_id_contains_feature.rst
  docs/_tooling/extensions/score_metamodel/tests/rst/options/test_options_extra_option.rst
  docs/_tooling/extensions/score_metamodel/tests/rst/options/test_options_options.rst
  docs/_tooling/extensions/score_metamodel/tests/test_rules_file_based.py
Labels: community:infrastructure
